### ISSUE TITLE
Searching units in unitconverter jumps to the main calulcator input field

### ISSUE THREAD

**Issue by Qik000** [Qalculate/qalculate-gtk#184]
Searching units in unitconverter jumps to the main calulcator input field causing me to constantly overwrite it, for example:

type in 3mi, and search for "km" the "k" gets typed in, but m is then places in the main input field overwriting everything that was in it.

**Comment by hanna-kn** [comment]
Fixed.

**Comment by Qik000** [comment]
I am on 3.12.1 and it is not fixed, as of your reply this was the newest version

**Comment by hanna-kn** [comment]
> I am on 3.12.1 and it is not fixed, as of your reply this was the newest version

It should be fixed in version 3.13 (2020-09-21).  When I replied, and closed the the issue, it was fixed in the development/git version.
