### ISSUE TITLE
hide variable/function/unit doesn't restore correctly

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/qalculate-gtk#583]
1. When I check hide variable/function/unit, it hide in original category, but it appear in user variables/functions/units. Should it only accessible by variable/function/unit manager?

2. When I uncheck hide variable/function/unit, it still appear in user variables/functions/units.

**Comment by hanna-kn** [comment]
Fixed (hidden objects no longer appears user objects menus).

**Comment by howaboutuser** [comment]
V5.5.1
1. When I hide "Pauli0", it still appear in recent used list.
2. When I show "Pauli0", it doesn't appear in "Matrices & Vectors". A variable with same name appear in "User variables".
3. When I hide "v1", it still appear in recent used list.
4. When I deactivate "v1", it still appear in recent used list.

**Comment by hanna-kn** [comment]
Fixed. 4 was caused by empty category field in matrix edit dialog.

**Comment by howaboutuser** [comment]
5. When I hide then show "BakersDozen", it appear in "User variables" and "Inactive".

**Comment by hanna-kn** [comment]
> 5. When I hide then show "BakersDozen", it appear in "User variables" and "Inactive".

If you edit a non-user object, the original object is deactivated and a new object is created. If you remove the new object, the original object is automatically reactivated. (Note that the Qt UI does not allow editing of non-user objects, only deactivation.)
